[2023-09-27T20:25:40.130-0400] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ETL_Server_Access_Log_Processing.transform manual__2023-09-28T00:15:13.137918+00:00 [queued]>
[2023-09-27T20:25:40.143-0400] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ETL_Server_Access_Log_Processing.transform manual__2023-09-28T00:15:13.137918+00:00 [queued]>
[2023-09-27T20:25:40.143-0400] {taskinstance.py:1359} INFO - Starting attempt 2 of 2
[2023-09-27T20:25:40.252-0400] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): transform> on 2023-09-28 00:15:13.137918+00:00
[2023-09-27T20:25:40.257-0400] {standard_task_runner.py:57} INFO - Started process 90877 to run task
[2023-09-27T20:25:40.259-0400] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'ETL_Server_Access_Log_Processing', 'transform', 'manual__2023-09-28T00:15:13.137918+00:00', '--job-id', '28', '--raw', '--subdir', 'DAGS_FOLDER/ETL_Server_Access_Log_Processing.py', '--cfg-path', '/tmp/tmp7lq_61rl']
[2023-09-27T20:25:40.260-0400] {standard_task_runner.py:85} INFO - Job 28: Subtask transform
[2023-09-27T20:25:40.375-0400] {task_command.py:415} INFO - Running <TaskInstance: ETL_Server_Access_Log_Processing.transform manual__2023-09-28T00:15:13.137918+00:00 [running]> on host erosennnin-TUF-Gaming-FX505DU-FX505DU
[2023-09-27T20:25:40.601-0400] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='ramesh@somemail.com' AIRFLOW_CTX_DAG_OWNER='Ramesh Sannareddy' AIRFLOW_CTX_DAG_ID='ETL_Server_Access_Log_Processing' AIRFLOW_CTX_TASK_ID='transform' AIRFLOW_CTX_EXECUTION_DATE='2023-09-28T00:15:13.137918+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-09-28T00:15:13.137918+00:00'
[2023-09-27T20:25:40.602-0400] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-09-27T20:25:40.602-0400] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'ls /home/erosennnin/Programing/Apache_Airflow/downloads/ && tr "[a-z]" "[A-Z]" < /home/erosennnin/Programing/Apache_Airflow/downloads/extracted.txt > /home/erosennnin/Programing/Apache_Airflow/downloads/capitalized.txt']
[2023-09-27T20:25:40.612-0400] {subprocess.py:86} INFO - Output:
[2023-09-27T20:25:40.614-0400] {subprocess.py:93} INFO - capitalized.txt
[2023-09-27T20:25:40.615-0400] {subprocess.py:93} INFO - web-server-access-log.txt
[2023-09-27T20:25:40.615-0400] {subprocess.py:93} INFO - /usr/bin/bash: line 1: /home/erosennnin/Programing/Apache_Airflow/downloads/extracted.txt: No such file or directory
[2023-09-27T20:25:40.615-0400] {subprocess.py:97} INFO - Command exited with return code 1
[2023-09-27T20:25:40.622-0400] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/erosennnin/anaconda3/envs/coursera/lib/python3.11/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-09-27T20:25:40.625-0400] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=ETL_Server_Access_Log_Processing, task_id=transform, execution_date=20230928T001513, start_date=20230928T002540, end_date=20230928T002540
[2023-09-27T20:25:40.741-0400] {standard_task_runner.py:104} ERROR - Failed to execute job 28 for task transform (Bash command failed. The command returned a non-zero exit code 1.; 90877)
[2023-09-27T20:25:40.752-0400] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-09-27T20:25:40.781-0400] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
