[2023-09-27T20:29:38.791-0400] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ETL_Server_Access_Log_Processing.load manual__2023-09-28T00:29:16.809110+00:00 [queued]>
[2023-09-27T20:29:38.797-0400] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ETL_Server_Access_Log_Processing.load manual__2023-09-28T00:29:16.809110+00:00 [queued]>
[2023-09-27T20:29:38.798-0400] {taskinstance.py:1359} INFO - Starting attempt 1 of 2
[2023-09-27T20:29:38.926-0400] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): load> on 2023-09-28 00:29:16.809110+00:00
[2023-09-27T20:29:38.932-0400] {standard_task_runner.py:57} INFO - Started process 91491 to run task
[2023-09-27T20:29:38.935-0400] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'ETL_Server_Access_Log_Processing', 'load', 'manual__2023-09-28T00:29:16.809110+00:00', '--job-id', '33', '--raw', '--subdir', 'DAGS_FOLDER/ETL_Server_Access_Log_Processing.py', '--cfg-path', '/tmp/tmpds87uba1']
[2023-09-27T20:29:38.937-0400] {standard_task_runner.py:85} INFO - Job 33: Subtask load
[2023-09-27T20:29:39.107-0400] {task_command.py:415} INFO - Running <TaskInstance: ETL_Server_Access_Log_Processing.load manual__2023-09-28T00:29:16.809110+00:00 [running]> on host erosennnin-TUF-Gaming-FX505DU-FX505DU
[2023-09-27T20:29:39.374-0400] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='ramesh@somemail.com' AIRFLOW_CTX_DAG_OWNER='Ramesh Sannareddy' AIRFLOW_CTX_DAG_ID='ETL_Server_Access_Log_Processing' AIRFLOW_CTX_TASK_ID='load' AIRFLOW_CTX_EXECUTION_DATE='2023-09-28T00:29:16.809110+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-09-28T00:29:16.809110+00:00'
[2023-09-27T20:29:39.376-0400] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-09-27T20:29:39.376-0400] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'zip log.zip capitalized.txt']
[2023-09-27T20:29:39.387-0400] {subprocess.py:86} INFO - Output:
[2023-09-27T20:29:39.412-0400] {subprocess.py:93} INFO - 	zip warning: name not matched: capitalized.txt
[2023-09-27T20:29:39.412-0400] {subprocess.py:93} INFO - 
[2023-09-27T20:29:39.413-0400] {subprocess.py:93} INFO - zip error: Nothing to do! (log.zip)
[2023-09-27T20:29:39.413-0400] {subprocess.py:97} INFO - Command exited with return code 12
[2023-09-27T20:29:39.425-0400] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/erosennnin/anaconda3/envs/coursera/lib/python3.11/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 12.
[2023-09-27T20:29:39.429-0400] {taskinstance.py:1398} INFO - Marking task as UP_FOR_RETRY. dag_id=ETL_Server_Access_Log_Processing, task_id=load, execution_date=20230928T002916, start_date=20230928T002938, end_date=20230928T002939
[2023-09-27T20:29:39.529-0400] {standard_task_runner.py:104} ERROR - Failed to execute job 33 for task load (Bash command failed. The command returned a non-zero exit code 12.; 91491)
[2023-09-27T20:29:39.547-0400] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-09-27T20:29:39.556-0400] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
